import pandas as pd

from .config import NETWORK_EVENTS_CSV


def _safe_numeric(row, column):
    """Return a valid numeric KPI value or None."""
    value = row.get(column)

    if value is None or pd.isna(value):
        return None

    try:
        value = float(value)
    except (TypeError, ValueError):
        return None

    if not pd.notna(value):
        return None

    return value


def load_operational_events():
    """
    Load network operational events generated by the
    network data pipeline.
    """

    if not NETWORK_EVENTS_CSV.exists():
        return pd.DataFrame()

    return pd.read_csv(
        NETWORK_EVENTS_CSV,
        parse_dates=["timestamp"]
    )


def detect_operational_events(network, anomalies):
    """
    Detect operational events by correlating each event
    with network KPI conditions near the event timestamp.
    """

    events = load_operational_events()

    if events.empty:
        return []

    network = network.copy()
    anomalies = anomalies.copy()
    events = events.copy()

    network["timestamp"] = pd.to_datetime(
        network["timestamp"]
    )

    anomalies["timestamp"] = pd.to_datetime(
        anomalies["timestamp"]
    )

    events["timestamp"] = pd.to_datetime(
        events["timestamp"]
    )

    network = network.sort_values(
        ["tower_id", "timestamp"]
    )

    anomalies = anomalies.sort_values(
        ["tower_id", "timestamp"]
    )

    results = []

    for _, event in events.iterrows():

        tower_id = event["tower_id"]
        event_time = event["timestamp"]

        tower_network = network[
            network["tower_id"] == tower_id
        ]

        tower_anomalies = anomalies[
            anomalies["tower_id"] == tower_id
        ]

        if tower_network.empty:
            continue

        # Find the KPI record closest to the event timestamp.
        tower_network = tower_network.copy()

        tower_network["time_distance"] = (
            tower_network["timestamp"] - event_time
        ).abs()

        nearest_kpi = tower_network.loc[
            tower_network["time_distance"].idxmin()
        ]

        # Ignore events that are too far away from
        # the available KPI observation.
        time_distance = (
            nearest_kpi["time_distance"]
        )

        if time_distance > pd.Timedelta(hours=2):
            continue

        kpi_abnormal = False

        if not tower_anomalies.empty:

            tower_anomalies = tower_anomalies.copy()

            tower_anomalies["time_distance"] = (
                tower_anomalies["timestamp"]
                - event_time
            ).abs()

            nearest_anomaly = tower_anomalies.loc[
                tower_anomalies["time_distance"].idxmin()
            ]

            if nearest_anomaly["time_distance"] <= pd.Timedelta(hours=2):
                anomaly_value = nearest_anomaly["is_anomaly"]

                if pd.notna(anomaly_value):
                    kpi_abnormal = bool(anomaly_value)

        reasons = []
        latency = _safe_numeric(nearest_kpi, "latency")
        packet_loss = _safe_numeric(nearest_kpi, "packet_loss")
        cpu = _safe_numeric(nearest_kpi, "cpu_usage")
        memory = _safe_numeric(nearest_kpi, "memory_usage")

        if latency is not None and latency > 100:
            reasons.append(
                f"High latency: {latency:.2f} ms"
            )

        if packet_loss is not None and packet_loss > 5:
            reasons.append(
                f"High packet loss: {packet_loss:.2f}%"
            )

        if cpu is not None and cpu > 85:
            reasons.append(
                f"High CPU utilization: {cpu:.1f}%"
            )

        if memory is not None and memory > 85:
            reasons.append(
                f"High memory utilization: {memory:.1f}%"
            )

        if kpi_abnormal:
            reasons.append(
                "Machine-learning anomaly detected"
            )

        event_severity = str(
            event.get(
                "severity",
                "NORMAL"
            )
        ).upper()

        trigger_investigation = False

        # High-severity operational events
        if event_severity in {
            "HIGH",
            "CRITICAL"
        }:
            trigger_investigation = True

        # Backhaul-specific correlation
        if event["event_type"] == "BACKHAUL":

            utilization = event.get(
                "backhaul_utilization",
                0
            )

            if (
                pd.notna(utilization)
                and float(utilization) >= 85
            ):
                trigger_investigation = True

                reasons.append(
                    f"High backhaul utilization: "
                    f"{float(utilization):.1f}%"
                )

        # KPI anomaly must be temporally correlated
        if kpi_abnormal:
            trigger_investigation = True

        # Configuration or maintenance events only
        # trigger investigation when there is supporting
        # KPI evidence near the event time.
        if event["event_type"] in {
            "CONFIGURATION",
            "MAINTENANCE"
        }:

            if reasons:
                trigger_investigation = True

        if not trigger_investigation:
            continue

        # Determine operational severity.
        if (
            (latency is not None and latency > 100)
            or (packet_loss is not None and packet_loss > 5)
        ):
            kpi_severity = "CRITICAL"
        elif (
            (latency is not None and latency > 80)
            or (packet_loss is not None and packet_loss > 3)
            or kpi_abnormal
        ):
            kpi_severity = "HIGH"
        else:
            kpi_severity = "NORMAL"

        if event_severity == "CRITICAL":
            operational_severity = "CRITICAL"
        elif event_severity == "HIGH":
            operational_severity = "HIGH"
        elif (
            event_severity == "MEDIUM"
            and kpi_severity in {"HIGH", "CRITICAL"}
        ):
            operational_severity = "HIGH"
        elif kpi_severity == "CRITICAL":
            operational_severity = "HIGH"
        elif kpi_severity == "HIGH":
            operational_severity = "MEDIUM"
        else:
            operational_severity = "LOW"

        results.append({
            "timestamp": (
                event_time.isoformat()
                if hasattr(event_time, "isoformat")
                else str(event_time)
            ),
            "tower_id": tower_id,
            "event_type": event["event_type"],
            "event_name": event["event_name"],
            "event_severity": event_severity,
            "kpi_severity": kpi_severity,
            "operational_severity": operational_severity,
            "kpi_status": (
                "ABNORMAL"
                if kpi_abnormal
                else "NORMAL"
            ),
            "trigger_investigation": True,
            "reason": (
                "; ".join(reasons)
                if reasons
                else str(event["description"])
            ),
            "description": event["description"],
            "kpi_timestamp": (
                nearest_kpi["timestamp"].isoformat()
                if hasattr(nearest_kpi["timestamp"], "isoformat")
                else str(nearest_kpi["timestamp"])
            ),
            "kpi_time_distance_minutes": (
                time_distance.total_seconds()
                / 60
            ),
        })

    return results
